name: Rust2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: compile
      run: cargo build --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: ${{ github.workspace }}/tes3/target/debug/deps/*
